# Generated by Django 3.1.2 on 2020-11-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecourse',
            old_name='course',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipeinformation',
            old_name='information',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipeinstruction',
            old_name='instruction',
            new_name='name',
        ),
    ]
