# Generated by Django 3.1.1 on 2020-11-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTest',
        ),
    ]
