# Generated by Django 3.1.2 on 2020-11-06 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20201106_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedietitem',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='recipeoccasionitem',
            name='occasion',
        ),
        migrations.AddField(
            model_name='recipedietitem',
            name='recipe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeoccasionitem',
            name='recipe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipedietitem',
            name='recipe_diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipediet'),
        ),
        migrations.AlterField(
            model_name='recipeoccasionitem',
            name='recipe_occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipeoccasion'),
        ),
    ]
