# Generated by Django 3.1.1 on 2020-11-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20201106_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecourse',
            name='image',
            field=models.ImageField(default='default_images/default_recipe_course_image.jpg', upload_to='recipe_course_pics/'),
        ),
        migrations.AddField(
            model_name='recipediet',
            name='image',
            field=models.ImageField(default='default_images/default_recipe_diet_image.jpg', upload_to='recipe_diet_pics/'),
        ),
        migrations.AddField(
            model_name='recipeoccasion',
            name='image',
            field=models.ImageField(default='default_images/default_recipe_occasion_image.jpg', upload_to='recipe_occasion_pics/'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(default='default_images/default_recipe_image.jpg', upload_to='recipe_pics/'),
        ),
    ]
