# Generated by Django 3.1.1 on 2020-11-12 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20201110_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCookingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_time', models.CharField(max_length=20)),
                ('cooking_time_max', models.IntegerField()),
                ('cooking_time_min', models.IntegerField()),
            ],
            options={
                'db_table': 'recipe_cooking_time',
            },
        ),
        migrations.CreateModel(
            name='RecipeCookingTimeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipecookingtime')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
            options={
                'db_table': 'recipe_cooking_time_item',
            },
        ),
    ]
