# Generated by Django 3.1.2 on 2020-10-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
