# Generated by Django 3.1.1 on 2020-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201115_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_images/avatars/avatar-flat-22.png', upload_to='profile_pics/'),
        ),
    ]
