# Generated by Django 3.1.1 on 2020-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Keyword')),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'search_keyword',
            },
        ),
    ]
